### ISSUE TITLE
unexpected error (HTTP 404) error

### ISSUE THREAD

**Issue by gru-cho** [lweller/xray-cucumber-intellij#7]
Hi,
After I click a download xray cucumber tests button, I encountered an error as "unexpected error(HTTP 404)".
I'm using jira cloud and PyCharm 2021.3.3 (Community Edition).
Any way I can fix it ?
Thanks a lot.

**Comment by lweller** [comment]
HTTP 404 error indicates, that the endpoint cannot be found. THis is either due to a misconfigured URL or a connectivity issue.
